package nl.kute.testobjects.kotlin.protectedvisibility

import nl.kute.testobjects.java.protectedvisibility.SubClassOfJavaClassWithProtectedProperty

class SubSubClassOfClassWithProtectedProperty : SubClassOfJavaClassWithProtectedProperty()