@file:Suppress("KDocUnresolvedReference", "SameParameterValue")

package nl.kute.reflection

import nl.kute.core.AsStringProducer
import nl.kute.core.namedvalues.NameValue
import nl.kute.reflection.error.SyntheticClassException
import kotlin.reflect.KClass
import kotlin.reflect.KProperty
import kotlin.reflect.KProperty1
import kotlin.reflect.full.memberProperties
import kotlin.reflect.jvm.jvmErasure

/**
 * These classes should not be included, these properties contain of meta info about objects being "asString-ed",
 * would make it verbose and confusing
 */
private val kutePropertyClassesToOmit: Array<Class<out Any>> =
    arrayOf(AsStringProducer::class.java, NameValue::class.java)

/** Property filter based on [kutePropertyClassesToOmit] (should be negated when applied) */
private val kutePropertyClassFilter: (KProperty<*>) -> Boolean =
    { property: KProperty<*> -> kutePropertyClassesToOmit.any { it.isAssignableFrom(property.returnType.jvmErasure.java) } }

/**
 * Get the properties from the class hierarchy (see [subSuperHierarchy]).
 * * In case of property overrides or name-shadowing, only the property from the most specific subclass
 *   is present in the result.
 *     * This implies that the properties are unique by name.
 * * The resulting properties are returned regardless of visibility.
 *   So not only `public` or `protected`, but also `internal` and `private` properties.
 * * The properties may or may not be accessible ([KProperty.isAccessible])
 */
@JvmSynthetic // avoid access from external Java code
internal fun <T : Any> KClass<T>.propertiesFromSubSuperHierarchy(): List<KProperty<*>> =
    propertiesFromHierarchy(mostSuper = false)

/**
 * Get the properties from the class hierarchy (see [subSuperHierarchy]).
 * * In case of property overrides or name-shadowing, only the property from the most specific subclass
 *   is present in the result.
 *     * This implies that the properties are unique by name.
 * * The resulting properties are returned regardless of visibility.
 *   So not only `public` or `protected`, but also `internal` and `private` properties.
 * * The properties may or may not be accessible ([KProperty.isAccessible])
 */
@Suppress("SameParameterValue")
private fun <T : Any> KClass<T>.propertiesFromHierarchy(mostSuper: Boolean, filterKuteProps: Boolean = true): List<KProperty<*>> {
    val classHierarchy: List<KClass<in T>> = if (mostSuper) this.superSubHierarchy() else this.subSuperHierarchy()
    val linkedHashSet: LinkedHashSet<KProperty1<T, *>> = linkedSetOf()
    return linkedHashSet.also { theSet ->
        @Suppress("UNCHECKED_CAST")
        theSet.addAll(
            classHierarchy.asSequence()
                .map { kClass ->
                    try {
                        kClass.memberProperties
                    } catch (e: UnsupportedOperationException) {
                        // UnsupportedOperationException may happen in these cases (from Kotlin exception message):
                        //   > 1. This class is an internal synthetic class generated by the Kotlin compiler,
                        //   >    such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc.
                        //   > 2. Packages and file facades are not yet supported in Kotlin reflection.
                        // In these somewhat exotic cases, as Kotlin can't find properties, we don't bother
                        //   > The message also suggest this: `Please use Java reflection to inspect this class`
                        //   > But that's out of scope for this more exotic stuff, we just don't care that much

                        // to be handled within Kute. Must not propagate to outside-world!
                        throw SyntheticClassException(e.message, e)
                    } catch (error: kotlin.reflect.jvm.internal.KotlinReflectionInternalError) {
                        // Kotlin's reflection can't handle some classes, typically Java classes with
                        // anonymous inner classes, etc.
                        // Normally one should *never* handle `Error`s, but neither in Java's nor in Kotlin's reflection
                        // there seems any way to reliably and viably determine these classes otherwise.
                        // Many operations (e.g. `memberProperties` or `superTypes`) on these classes will throw
                        // kotlin.reflect.jvm.internal.KotlinReflectionInternalError
                        throw SyntheticClassException(error.message, error)
                    }
                }
                .flatten()
                // include private properties only if in the class itself, not if it's in a superclass
                // note that Kotlin regards protected stuff as private! (also with Java package level)
                .filter { !it.isPrivate() || it.declaringClass() == this }
                // In case of overloads or name-shadowing, keep the property that is first in the hierarchy
                .distinctBy { prop -> prop.name }
                .filterNot { filterKuteProps && kutePropertyClassFilter.invoke(it) }
                .toList() as List<KProperty1<T, *>>
        )
    }.toList()
}
